/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import controlador.Controlador;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Producto;

/**
 *
 * @author simon
 */
public class Listar extends javax.swing.JFrame {
    DefaultTableModel table1;
    Controlador consulta;
    ArrayList<Producto> lista;
    Integer varModificar;
    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
        table1 = new DefaultTableModel();
        table1.addColumn("Codigo");
        table1.addColumn("Nombre");
        table1.addColumn("Marca");
        table1.addColumn("Categoria");
        table1.addColumn("Precio");
        table1.addColumn("Stock");
        jTable1.setModel(table1);
        consulta= new Controlador();
        varCodigo.addKeyListener(new KeyAdapter()
                                        {
                                           @Override
                                           public void keyTyped(KeyEvent e)
                                           {
                                              char caracter = e.getKeyChar();

                                              // Verificar si la tecla pulsada no es un digito
                                              if(((caracter < '0') ||
                                                 (caracter > '9')) &&
                                                 (caracter != '\b' /*corresponde a BACK_SPACE*/))
                                              {
                                                 e.consume();  // ignorar el evento de teclado
                                              }
                                            }
                                         }
                                    );
    //codigo, nombre_deporte, descripcion,tipo,peso,diametro,rebote,color,material
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonActualizar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        varCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonSalir.setText("Menu");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo producto:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(618, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(botonActualizar))
                                .addGap(18, 18, 18)
                                .addComponent(varCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBuscar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonBorrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonModificar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonActualizar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscar)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
       // int rut,codigoCurso;
        //String nombre,apellido,dv;getrwo >0 remove0
        while(table1.getRowCount()>0) table1.removeRow(0);
        this.varCodigo.setText(null);
        lista = consulta.Listar(); 
        Object[] fila = new Object[6];
        for (int x=0;x<lista.size();x++){
            fila[0]=lista.get(x).getCodigo();
            fila[1]=lista.get(x).getNombre();
            fila[2]=lista.get(x).getMarca();
            fila[3]=lista.get(x).getCategoria();
            fila[4]=lista.get(x).getPrecio();
            fila[5]=lista.get(x).getStock();
            table1.addRow(fila);
        }jTable1.updateUI();
        JOptionPane.showMessageDialog(this, "Lista actualizada");
        
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        JFrame salir = new Menu();
        salir.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        consulta = new Controlador();
        if ( !varCodigo.getText().isEmpty()){
            while(table1.getRowCount()>0) table1.removeRow(0);
            lista = consulta.Buscar(Integer.parseInt(varCodigo.getText()));
            Object[] fila = new Object[6];
        for (int x=0;x<lista.size();x++){
            fila[0]=lista.get(x).getCodigo();
            fila[1]=lista.get(x).getNombre();
            fila[2]=lista.get(x).getMarca();
            fila[3]=lista.get(x).getCategoria();
            fila[4]=lista.get(x).getPrecio();
            fila[5]=lista.get(x).getStock();
                table1.addRow(fila);
            }jTable1.updateUI();
            if (table1.getRowCount()>0){
                consulta.Eliminar(Integer.parseInt(varCodigo.getText()));
                JOptionPane.showMessageDialog(this, "Eliminado con exito");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro coincidencia");
            }
        }else {
                JOptionPane.showMessageDialog(this, "Ingrese campo");

        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        while(table1.getRowCount()>0) table1.removeRow(0);
        if ( !varCodigo.getText().isEmpty()){
            lista = consulta.Buscar(Integer.parseInt(varCodigo.getText()));
            Object[] fila = new Object[6];
                for (int x=0;x<lista.size();x++){
                    fila[0]=lista.get(x).getCodigo();
                    fila[1]=lista.get(x).getNombre();
                    fila[2]=lista.get(x).getMarca();
                    fila[3]=lista.get(x).getCategoria();
                    fila[4]=lista.get(x).getPrecio();
                    fila[5]=lista.get(x).getStock();
                table1.addRow(fila);
            }jTable1.updateUI();
            if (table1.getRowCount()>0){
                JOptionPane.showMessageDialog(this, "Producto encontrado");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro coincidencia");
            }
        } else {
                JOptionPane.showMessageDialog(this, "Ingrese campo");

        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        int codigo;
        Producto producto;
        if ( !varCodigo.getText().isEmpty()){
            lista = consulta.Buscar(Integer.parseInt(varCodigo.getText()));
            if(!lista.isEmpty()){
            producto = lista.get(0);
                JOptionPane.showMessageDialog(this, "Producto encontrado");
                JFrame modificar = new Modificar(producto.getCodigo()+"");
                modificar.setVisible(true);
            dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro coincidencia");
            }
        } else {
                JOptionPane.showMessageDialog(this, "Ingrese campo");

        }    
    }//GEN-LAST:event_botonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField varCodigo;
    // End of variables declaration//GEN-END:variables
}
